### ISSUE TITLE
Madison + Ruby: Chicago

### ISSUE THREAD

**Issue by torgoton** [tech-conferences/confs.tech#101]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] UX / Design
- [ ] iOS
- [ ] Android
- [X] Ruby
- [ ] General

```json
  {
    "name": "Madison+ Ruby: Chicago",
    "url": "https://ti.to/adorable/madison-ruby-chicago",
    "startDate": "2018-05-10",
    "endDate": "2018-05-11",
    "city": "Chicago, IL",
    "country": "USA",
    "cfpUrl": "https://www.papercall.io/madison-ruby-chicago",
    "cfpEndDate": "2018-03-16",
    "twitter": "@tMadisonRuby"
  }
```

**Comment by nimzco** [comment]
Thanks, I've just added it! 👍
