### ISSUE TITLE
Hacker Hostel

### ISSUE THREAD

**Issue by kulkidz91** [tech-conferences/confs.tech#107]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] UX / Design
- [ ] iOS
- [ ] Android
- [ ] Ruby
- [ ] General

```json
  {
    "name": "Hacker Hostel",
    "url": "
![you don t have to choose between a boring internship and an awesome vacation 1](https://user-images.githubusercontent.com/8042996/35773309-3af10c86-091c-11e8-8d35-c03f63550191.jpg)
https://www.hackerhostel.com.jm/",
    "startDate": "2018-05-01",
    "endDate": "2018-05-31",
    "city": "Kingston",
    "country": "Jamaica",
    "cfpUrl": "https://www.hackerhostel.com.jm/",
    "cfpEndDate": "2018-07-01",
    "twitter": "@twitter_handle"
  }
```

**Comment by nimzco** [comment]
Hi there!
Thanks for your contribution but it's not really a conference, therefor it does not fit in this listing. 
Thanks a lot though!
