### ISSUE TITLE
How.Camp 2018 Sofia

### ISSUE THREAD

**Issue by bogomil** [tech-conferences/confs.tech#112]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ x] UX / Design
- [ ] iOS
- [ ] Android
- [ ] Ruby
- [ ] General

```json
  {
    "name": "How.Camp 2018 Sofia",
    "url": "http://how.camp",
    "startDate": "2018-04-13",
    "endDate": "2018-04-13",
    "city": "Sofia",
    "country": "Bulgaria",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@bgwebsummmit"
  }
```

**Comment by bogomil** [comment]
Please add our small event into your awesome list :)

**Comment by trivikr** [comment]
Bulgaria Web Summit is already present in our list https://confs.tech/javascript/Bulgaria

**Comment by nimzco** [comment]
I've added the twitter handle. I'll close the issue 👍
