### ISSUE TITLE
Experience Conference 2018

### ISSUE THREAD

**Issue by iKristy** [tech-conferences/confs.tech#121]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] CSS
- [x] UX / Design
- [ ] Ruby
- [ ] iOS / Swift
- [ ] Android
- [ ] PHP
- [ ] General

```json
  {
    "name": "Experience Conference",
    "url": "http://www.exconf.com",
    "startDate": "2018-03-26",
    "endDate": "2018-03-27",
    "city": "Bratislava",
    "country": "Slovakia",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@exconfba"
  }
```

**Comment by trivikr** [comment]
Thanks! 😄
Added in https://github.com/tech-conferences/confs.tech/commit/0b4af9d05c4a1b6d43afd6e14054b61f18d4e8a1
