### ISSUE TITLE
Add Android tag to Appdevcon conference

### ISSUE THREAD

**Issue by davidmigloz** [tech-conferences/confs.tech#126]
Currently [Appdevcon](http://appdevcon.nl/) has just `#ios` tag.
The conference also covers Android topics, so it would be nice if you could also add `#android` tag.

https://confs.tech/ios/Netherlands

Thanks!

**Comment by nimzco** [comment]
Done! Thanks for letting us know. 👍

**Comment by davidmigloz** [comment]
Thanks! :)
