### ISSUE TITLE
API the Docs Paris

### ISSUE THREAD

**Issue by katalinfogas** [tech-conferences/confs.tech#127]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] CSS
- [ ] UX / Design
- [ ] Ruby
- [ ] iOS / Swift
- [ ] Android
- [ ] PHP
- [ ] Data
- [ x] Tech-comm
- [ ] General

```json
  {
    "name": "API the Docs Paris 2018",
    "url": "https://www.eventbrite.com/e/api-the-docs-paris-2018-tickets-42858996412?aff=es2",
    "startDate": "2018-04-24",
    "endDate": "2018-04-24",
    "city": "Paris",
    "country": "France",
    "cfpUrl": "https://www.papercall.io/apithedocsparis2018",
    "cfpEndDate": "2018-03-18",
    "twitter": "@APItheDocs"
  }
```

**Comment by nimzco** [comment]
I've added it, thank you! 👍
