### ISSUE TITLE
Going directly to https://confs.tech/javascript/U.S.A. shows no results

### ISSUE THREAD

**Issue by akinnee** [tech-conferences/confs.tech#129]
Going directly to https://confs.tech/javascript/U.S.A. shows no results. I have to go to https://confs.tech and then click javascript and USA to see results.

**Comment by nimzco** [comment]
Hi @akinnee!
It works for me when I go to [https://confs.tech/javascript/U.S.A.](https://confs.tech/javascript/U.S.A.) it loads correctly, but you have to have `U.S.A.` written with a `.` at the end. Was that the problem?
