### ISSUE TITLE
Nothing happens when submitting a new event

### ISSUE THREAD

**Issue by vincentzimmer** [tech-conferences/confs.tech#149]
No redirection when clicking on the button submit from the new event form.

**Comment by nimzco** [comment]
Oh it is probably because there was an error and I don't show it yet.
I'll update that, thanks for letting us know. 👍

**Comment by nimzco** [comment]
This should fix the problem: https://github.com/tech-conferences/confs.tech/commit/66e175019df020e46891a3efa87b9def7ffa2a4d
