### ISSUE TITLE
More source to get conferences from

### ISSUE THREAD

**Issue by veggiemonk** [tech-conferences/confs.tech#156]
Hi, 

I found that many conferences are missing. Do you think it would be doable to pull then automatically from there: https://10times.com/technology ?

**Comment by nimzco** [comment]
We could write a script, pull them from there and put it in the `general` list I suppose. If you want to try to write a scraper, do it! 👍

**Comment by veggiemonk** [comment]
@nimzco I'll try but can't promise I'll do it soon

**Comment by nimzco** [comment]
No worries, I know how time consuming it is :)
