### ISSUE TITLE
Feature request: video search

### ISSUE THREAD

**Issue by lesyk** [tech-conferences/confs.tech#174]
Hi there,

Thanks for a good resource. Sometime ago I was thinking for a same-ish thing to make, but besides just maintaining list of conferences I was planning to add also videos (links on videos, or embed them from youtube), together with rating for them and a search. Maybe it is somethings which you are willing to invest time into.

Thank you guys!

**Comment by nimzco** [comment]
Hey @lesyk ! Thanks for the support and your suggestion.

That'd be great but I don't think either of us have time to add such a feature for now. I think the important focus right now is making sure we have a comprehensive and qualitative list of conferences for each topic we are covering.

Hopefully in the future we'll look into that! :)

Cheers!

**Comment by eduardsi** [comment]
Hey, @lesyk! 

I hope you will find [dev.tube](https://dev.tube) helpful. It's the tech video hub maintained by the dev community.
