### ISSUE TITLE
Importing large list

### ISSUE THREAD

**Issue by karllhughes** [tech-conferences/confs.tech#184]
Hey, y'all,
I have a big list of conferences that I curate too: https://airtable.com/shry5mX0LQOFa0rnw

I'd like to merge it in with y'all's data. Any chance you've built a CSV to JSON converter before that I can use? Otherwise, I may tackle writing it so we can keep our lists in sync.

Nice work!

**Comment by nimzco** [comment]
Hi @karllhughes !
Nice list, thank you! We don't have any converter unfortunately. 

Once converted, you can check duplicates by running these tests: https://github.com/tech-conferences/confs.tech/blob/master/src/components/App/tests/conferences.test.js

Thank you so much! 👍

**Comment by karllhughes** [comment]
Ok, I'll make myself a note to do this sometime in the next couple weeks.

Thanks for the quick response!
