### ISSUE TITLE
React Native App

### ISSUE THREAD

**Issue by leonardo2204** [tech-conferences/confs.tech#215]
Hey guys, first of all,  nice work!

I've been thinking about creating a simple app to better filter and show confs, what do you guys think?
I already have an open source RN Map-alike app, so it's as simple as adapting to this.

Thanks!

**Comment by trivikr** [comment]
Oh, that would be wonderful!

**Comment by prigara** [comment]
Yes, that would be really cool!

**Comment by nimzco** [comment]
That’s a great idea!
We use Algolia for filtering on our side. They have a good React API, you can check out how we do it on this repo or their doc is ok.

You should be able to find the public API key on confs.tech.

**Comment by leonardo2204** [comment]
That's cool, gonna dig into their docs!
As soon as I can I'll start the project under my account, and I'll let you guys know!
And of course, contributions are more than welcome!

Thanks for the great job here!

**Comment by leonardo2204** [comment]
Just letting you guys know, it is live!
I'm starting to track the issues (actually milestones) of what we should do, so I'd be happy to see a lot of contributions from you guys!
[https://github.com/leonardo2204/confstech-mobile](https://github.com/leonardo2204/confstech-mobile)

Thanks guys!

**Comment by trivikr** [comment]
That was quick!
Thanks @leonardo2204

**Comment by trivikr** [comment]
I'd worked with ReactNative back in late-2016, will check out your app over the weekend of May 5th

**Comment by leonardo2204** [comment]
Sure, no problem!
But actually I've just started the project, there is a lot of improvements to do (specially with UI), but good news is that we can use lot of the React logic from the website :)
I've also created some issues to track things, like who is doing what to keep it organized!

Thanks man!

**Comment by leonardo2204** [comment]
No problem, I'm happy I can help, it's been a struggle for me to find cool confs, the website really has really helped me!
So, not really, I've just begun coding, so I don't have an ipk or apk to test, but if you don't mind, it's really easy to run react-native locally, as long as you have xcode (which I guess you do).
But as soon as I have a working stable version I'm more than happy to release test builds!

Speaking of which, I don't have a personal apple account, only Google Play, so does anyone own on, to be able to launch the app in the app store? Otherwise I'd have to pay $99 yearly just for it!

Thanks again guys!

**Comment by nimzco** [comment]
Oh that's a good concern, I don't have an Apple developer account neither. Let's start with the Google Play store and we'll see for the app store later.
To be fair, 80% of our traffic is desktop so it's not the end of the world if we're not on the AppStore I think.

**Comment by leonardo2204** [comment]
Sure, sounds like a plan!
And I agree, being in the Play Store is a beginning, if we have a good user feedback, we can think about going to the app store.

Thanks!

**Comment by leonardo2204** [comment]
Hey guys, sorry for the long delay, I've been working a lot recently, so I wasn't able to finish the app.
Anyway, I'm almost done with the alpha release which includes (for now) showing the confs, sorted and grouped by month + year.
I just have a small bug I'm struggling with, if you guys could help me would be awesome! [https://stackoverflow.com/questions/50309788/footer-along-with-searchbar-not-properly-shown-in-flatlist](https://stackoverflow.com/questions/50309788/footer-along-with-searchbar-not-properly-shown-in-flatlist)
Resolving this will make it almost done to submit to Google Play and see what happens :)

**Comment by nimzco** [comment]
Hey @leonardo2204 ! Sorry if I didn't respond earlier, I'm very busy these days. I'm happy to see you've got some answers on your question! 👍
