### ISSUE TITLE
Switch to lint-staged

### ISSUE THREAD

**Issue by prigara** [tech-conferences/confs.tech#216]
husky runs a pre-commit hook that lints all the JS files in the project even when I just add a new conference and edit JSON files.
With [lint-staged ](https://github.com/okonet/lint-staged) we can differentiate between commits with only JSON files and JS files.
What do you think?

**Comment by trivikr** [comment]
Sounds good. I've used husky+lint-staged in some of my projects and it was very helpful.
We can also run prettier in the pre-commit hook.

**Comment by prigara** [comment]
@nimzco 🙌Will give it a try tomorrow!

**Comment by prigara** [comment]
Works great! Thank you!
