### ISSUE TITLE
Conf sorting directly in Algolia

### ISSUE THREAD

**Issue by leonardo2204** [tech-conferences/confs.tech#245]
Hey guys, 
I'm kinda going through the code and I've realized that you've been sorting the confs in the frontend level, not back.
Doesn't it make more sense to sort by date in the back(algolia)?

https://www.algolia.com/doc/guides/ranking/sorting/

**Comment by nimzco** [comment]
Hey @leonardo2204, what do you mean exactly? The conferences are sorted in the backend already, I actually just group them by month and group the month.

What I do though is that I ask for only upcoming conferences. See: 
https://github.com/tech-conferences/confs.tech/blob/10e090a79cb82a5fa15d0dfa028c4fca1038af7d/src/components/ConferencePage/ConferencePage.js#L65

Let me know if that's not clear or if I can help more.

**Comment by leonardo2204** [comment]
You are right, I was mistaken with the cfp sorting, sorry about that!
________________________________
De: Nima Izadi <notifications@github.com>
Enviado: quinta-feira, 3 de maio de 2018 19:57
Para: tech-conferences/confs.tech
Cc: Leonardo Ferrari; Mention
Assunto: Re: [tech-conferences/confs.tech] Conf sorting directly in Algolia (#245)


Hey @leonardo2204<https://github.com/leonardo2204>, what do you mean exactly? The conferences are sorted in the backend already, I actually just group them by month and group the month.

What I do though is that I ask for only upcoming conferences. See:
https://github.com/tech-conferences/confs.tech/blob/10e090a79cb82a5fa15d0dfa028c4fca1038af7d/src/components/ConferencePage/ConferencePage.js#L65

Let me know if that's not clear or if I can help more.

**Comment by nimzco** [comment]
No worries! I'll close the issue then ;)
