### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by huguestennier** [tech-conferences/confs.tech#256]
Hey guys!

First of all, props on the work! 

As you probably know, web accessibility is super important and impact everyone. I would like to help by doing an accessibility assessment and fixing the issues I find. 

I already opened a PR #253  regarding color ratios and was planning to do more - but first I wanted to take your pulse if you're interested or maybe that was on your roadmap already.

Thanks!

**Comment by nimzco** [comment]
Thanks Hugues! I definitely love this idea, thank you for doing that, I hope there are not too many issues to fix! 😬

**Comment by devcer** [comment]
Hey, can I help you with this? Let me know how I could help you.

**Comment by nimzco** [comment]
You can definitely help if you want, thank you!
I never found the time to rebase everything on the PR and make it work unfortunately..!
You can probably take a look at the open PR and go from there.

**Comment by nimzco** [comment]
I was talking about this PR: https://github.com/tech-conferences/confs.tech/pull/264

**Comment by nimzco** [comment]
Closing since https://github.com/tech-conferences/confs.tech/pull/498 merged.
