### ISSUE TITLE
Add FITC Amsterdam 2019 conference

### ISSUE THREAD

**Issue by funky-monkey** [tech-conferences/confs.tech#273]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] CSS
- [x] UX / Design
- [ ] Ruby
- [x] iOS / Swift
- [x] Android
- [ ] PHP
- [ ] Dev Ops
- [x] Data / AI
- [ ] Tech-comm
- [ ] Rust
- [ ] Golang
- [ ] Python
- [ ] Elixir
- [ ] Scala
- [x] General

```json
  {
    "name": "FITC Amsterdam 2019",
    "url": "http://fitc.ca/event/am19/",
    "startDate": "2018-02-18",
    "endDate": "2018-02-19",
    "city": "Amsterdam",
    "country": "The Netherlands",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@fitc"
  }
```

**Comment by nimzco** [comment]
Thanks for these additions, I've added them 👍
