### ISSUE TITLE
Bot is broken?

### ISSUE THREAD

**Issue by funky-monkey** [tech-conferences/confs.tech#275]
Hey, 
I've just added a conf via https://confs.tech/conferences/new and it adds it via your bot as a [pull request](https://github.com/tech-conferences/confs.tech/pull/271).

This only works one time however - I've tried 4 times adding the same and different conferences but with no luck. After that I've added them via opening an issue on github.
I have no browser plugins that stop advertisement or something similar.

Hope this helps,
Sidney

**Comment by nimzco** [comment]
Thanks for reporting this, I think I know why this happened. I think it happened when someone submits the same conference because the name of the branch is generated based of that.
Anyway I'll fix that, thanks!

**Comment by nimzco** [comment]
It should be fixed now! 👍

**Comment by funky-monkey** [comment]
Thanks for the quick response and glad to help! 
PS. Love this site, I was looking for a definitive resource when it comes to tech confs and i think i've found it, I'll add as many as i can if i find new ones!

**Comment by nimzco** [comment]
Thank you @funky-monkey ! 😄
