### ISSUE TITLE
WebExpo

### ISSUE THREAD

**Issue by iKristy** [tech-conferences/confs.tech#29]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "WebExpo",
    "url": "https://www.webexpo.net/",
    "startDate": "2018-09-22",
    "endtDate": "2018-09-23",
    "city": "Prague",
    "country": "Czech Republic",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@webexpo",
  }
```

**Comment by nimzco** [comment]
Awesome, thanks! 👍

**Comment by iKristy** [comment]
@nimzco: Damn, sorry. I meant to add it for 2017, didn't notice the template was for 2018. Apologies!! 🙈

**Comment by nimzco** [comment]
Oh no problem, I'll fix that right away!
