### ISSUE TITLE
Xperience By Design

### ISSUE THREAD

**Issue by iKristy** [tech-conferences/confs.tech#30]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "Xperience By Design",
    "url": "http://xperience.bydesignconf.com/",
    "startDate": "2017-10-27",
    "endtDate": "2017-10-27",
    "city": "Prague",
    "country": "Czech Republic",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@bydesignconf",
  }
```

**Comment by nimzco** [comment]
Awesome, thanks! I've added it too! 👍
