### ISSUE TITLE
CSS Day + UX Special

### ISSUE THREAD

**Issue by pp-koch** [tech-conferences/confs.tech#31]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [ ] iOS
- [ ] Ruby
- [x] CSS

```json
  {
    "name": "CSS Day + UX Special",
    "url": "https://cssday.nl/2018",
    "startDate": "2018-06-14",
    "endtDate": "2018-06-15",
    "city": "Amsterdam",
    "country": "Netherlands",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@cssdayconf",
  }
```

**Comment by nimzco** [comment]
Awesome, thanks! Adding this right away.
