### ISSUE TITLE
Submitting via web does not work for topic Security

### ISSUE THREAD

**Issue by Aelindara** [tech-conferences/confs.tech#358]
I just added some conferences via the web form. One does not get through.

I check "I'm not a Robot", klick "Submit", it shows "Submitting" just briefly and the page stays the same. I do not get directed to the confirmation page and no pull request is created.

The only difference (I can see) between the privious conferences I added and the not working one is the topic "Security".

![screenshot](https://user-images.githubusercontent.com/37771623/42513801-21a23bb2-8458-11e8-9a83-2fea66cbbb0d.jpg)

**Comment by nimzco** [comment]
Oh I actually found the problem. The backend didn't have the `security` topic registered...
Sorry about that, I'm fixing it right now and submitting the conference!

**Comment by nimzco** [comment]
https://github.com/tech-conferences/confs.tech/pull/359 🚀 
Thanks again @Aelindara !
