### ISSUE TITLE
Add CSSConf Budapest

### ISSUE THREAD

**Issue by lukeb-uk** [tech-conferences/confs.tech#36]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [X] CSS
- [ ] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "CSSConf Budapest",
    "url": "http://cssconfbp.rocks/",
    "startDate": "2017-10-25",
    "endDate": "2017-10-25",
    "city": "Budapest",
    "country": "Hungary",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@cssconfbudapest",
  }
```

**Comment by nimzco** [comment]
Awesome thanks, I've added it 👍
