### ISSUE TITLE
Feature Request: "General" or catch-all category

### ISSUE THREAD

**Issue by dentemple** [tech-conferences/confs.tech#37]
Hi, I'd like to request a "general" category for tech conferences, for conferences that don't fall under a specific stack or paradigm.

There are two conferences in the Northeast US that might be nice to add but don't quite have categories here: [Tech Bash 2017](https://techbash.com/) (Oct 3-6) and [Codeland Conf 2018](http://codelandconf.com/) (May 4-5).

**Comment by nimzco** [comment]
Hi Dentemple, that sounds legitimate to me. There is a bunch of tech conferences that are pretty generalist that could fall under that.

@prigara any objections / thoughts?

**Comment by prigara** [comment]
@dentemple, @nimzco sounds reasonable, let's add a new category.

**Comment by nimzco** [comment]
🎉
