### ISSUE TITLE
Improve font loading

### ISSUE THREAD

**Issue by nimzco** [tech-conferences/confs.tech#373]
- Use `preload`
- self host the font
- Promise based font loading 
- font-display swap

Thanks for enlighting me @magalhini!

**Comment by devcer** [comment]
Is this using FontFace? Can I work on this?

**Comment by nimzco** [comment]
We are using google fonts but fore sure feel free to work on it! Thanks! 😁

**Comment by nimzco** [comment]
Or are you talking about: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face ? 🤔

**Comment by devcer** [comment]
I'm talking about this -> https://usefulangle.com/post/74/javascript-dynamic-font-loading
This one looks like a promise based font loading. what do you think?

**Comment by nimzco** [comment]
Oh I didn’t know about this. That might be interesting to have a look. Maybe there are specifics helpers for React.

@magalhini, have you ever used this?
