### ISSUE TITLE
Get rid of the any types

### ISSUE THREAD

**Issue by nimzco** [tech-conferences/confs.tech#386]

**Comment by devcer** [comment]
Can I start working on this?

**Comment by nimzco** [comment]
Yes definitely, feel free! No one is working on the website right now and in the foreseeable future so feel free to tackle this or any other thing you want! 😊
Thank you!

**Comment by devcer** [comment]
Submitted a PR. If I'm doing it right then let me know so that I can also work on the remaining possible types. :)

**Comment by nimzco** [comment]
Thank you so much @devcer!
