### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by asednev** [tech-conferences/confs.tech#402]
Please add RSS feed which will help to stay on top of new conferences as they get added.

**Comment by nimzco** [comment]
Hey @asednev, until we implement that feature, you can follow our twitter account:
https://twitter.com/confstech which tweets every time a conference is added!

**Comment by tripu** [comment]
+1 !

**Comment by unicorncoding** [comment]
@tripu @asednev check out [dev.events](https://dev.events) for RSS support

**Comment by tripu** [comment]
Thanks for the pointer, @unicorncoding!

**Comment by hhkaos** [comment]
@unicorncoding is there an RSS for CFP? @nimzco maybe now that hacktoberfest is coming this could a feature that could be done by the community. Does it make sense?

**Comment by nimzco** [comment]
Hey @hhkaos!
Thank you for the suggestion.

Could something like that do the trick? https://github.com/tech-conferences/api.confs.tech/pull/71

**Comment by Fleker** [comment]
I was looking for this feature too. I took a look at the RSS feed example and it looks good.

**Comment by hhkaos** [comment]
Ey @nimzco ! 

> Hey @hhkaos! Thank you for the suggestion.
> 
> Could something like that do the trick? [tech-conferences/api.confs.tech#71](https://github.com/tech-conferences/api.confs.tech/pull/71)

I'm so sorry, I missed this message!. Yes I think it would. I see it was never merged, right? 

Thanks again

**Comment by nimzco** [comment]
Oh wow, a very old PR! Let me merge that in! The RSS for upcoming conferences is live already, but it's under this URL:
https://confs-tech-api.herokuapp.com/api/conferences.rss

Now the CFP rss is here: https://confs-tech-api.herokuapp.com/api/conferences/cfp.rss
