### ISSUE TITLE
Using CRA without Ejecting

### ISSUE THREAD

**Issue by trivikr** [tech-conferences/confs.tech#408]
Hi team,

We added Greenkeeper to our project in #394

Since then it has created 10+ PRs https://github.com/tech-conferences/confs.tech/labels/greenkeeper
These many PRs are created because our CRA app is ejected.

How about re-creating our App without Ejecting?
It'll be easier to maintain this project.

Regards,
Trivikram

**Comment by prigara** [comment]
Hey, 
That would be nice. [react-scripts-ts](https://www.npmjs.com/package/react-scripts-ts) seems to be well-maintained and already uses TS 3.1. I guess it's worth the try.

**Comment by nimzco** [comment]
For sure! I did it at the time to add TS and CSS modules I think.

I don’t have much time to do it though, if you do feel free to :fire: everything!

**Comment by nimzco** [comment]
🎉

**Comment by nimzco** [comment]
No way I was manually upgrading webpack versions 😄
