### ISSUE TITLE
Epicurrence

### ISSUE THREAD

**Issue by ImanGhader** [tech-conferences/confs.tech#42]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "Eppicurance",
    "url": "https://www.epicurrence.com/",
    "startDate": "2017-10-23",
    "endtDate": "2017-10-27",
    "city": "Utah",
    "country": "USA",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@Epicurrence",
  }
```

**Comment by nimzco** [comment]
👍 Thanks for all your issues, I'll close as I'll add them.
