### ISSUE TITLE
Add call for paper / call for speaker info

### ISSUE THREAD

**Issue by truongsinh** [tech-conferences/confs.tech#432]
It would be nice that besides name, place, popularity, theme and time of of the conference, we also have the indication whether the conference is calling for paper / speaker, and when is the deadline of such CfP

**Comment by cgrail** [comment]
@truongsinh what do you mean by that?

**Comment by truongsinh** [comment]
I updated the description

**Comment by prigara** [comment]
@truongsinh you can see CFP now: https://confs.tech/cfp/
@cgrail @nimzco we should probably make the link a bit more discoverable - now it's at the very bottom of the page, after our long list of events.

**Comment by nimzco** [comment]
Hey folks! Yes indeed, I've been wanted to do that for months now but never really know how to do it. 
I'll move forward with a simple change like this for now:

![image](https://user-images.githubusercontent.com/445045/55293241-59fca080-53c2-11e9-99a6-e48b31541040.png)


If you have any other suggestion for a better way to display the link, let me know 😄
