### ISSUE TITLE
Showing same conference in two months ( javascript, India )

### ISSUE THREAD

**Issue by thhmoc67** [tech-conferences/confs.tech#434]
React India conference will be in Sept'19 but it is showing in Aug'19 also. I did not found the exact problem so i am submitting the issue here. 

https://confs.tech/?topics=javascript&countries=India
![image](https://user-images.githubusercontent.com/15047392/55778396-771b2880-5ac0-11e9-9c91-c02611006d90.png)

**Comment by cgrail** [comment]
@thhmoc67 thanks a lot for bringing up this issue. I think initially the conference was scheduled for August, but then rescheduled for September. I've now removed the wrong entry from our database. Thanks again for your help. 👍
