### ISSUE TITLE
Json API/query params

### ISSUE THREAD

**Issue by funky-monkey** [tech-conferences/confs.tech#438]
Hi, 

I just love your website/project! (Also added some entries to it)

Since all the conferences are stored in plain JSON files, is there a way to get them out with an 'simple' API? Or maybe with a parameter in the URL? In a way i can query on year/location/topic?

Best,
Sidney

**Comment by nimzco** [comment]
Hi @funky-monkey!

Unfortunately, we don't have any public endpoint. :/

**Comment by EdwinMeijne** [comment]
You could simply call the existing .json files directly on github.

**Comment by funky-monkey** [comment]
Thanks! Ill try that!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
