### ISSUE TITLE
SSL Certificate Expired ? 

### ISSUE THREAD

**Issue by shrej** [tech-conferences/confs.tech#449]
I am unable to reach the app on Monday July 15 @ 1.15 PM Eastern. 

![image](https://user-images.githubusercontent.com/12212922/61234989-723ec400-a702-11e9-8732-a0188f041a12.png)

Looks like we are encountering [this](https://support.cloudflare.com/hc/en-us/articles/115003011431#525error) issue ?

**Comment by nimzco** [comment]
Hi @shrej, thanks for reporting the issue, we've just fixed it!
