### ISSUE TITLE
Request to update twitter URL

### ISSUE THREAD

**Issue by LitoChris** [tech-conferences/confs.tech#461]
Hello :-)

I uploaded our CloudNein Conference (Berlin, Germany・April 27-28), on Confs.Tech and the twitter URL I added is wrong. Could you please replace with the one below?https://twitter.com/cloudnein_conf

Thank you, Lito

**Comment by prigara** [comment]
Hi,

Done: https://github.com/tech-conferences/conference-data/pull/1717
