### ISSUE TITLE
How to remove an event?

### ISSUE THREAD

**Issue by AmandaPerino** [tech-conferences/confs.tech#466]
Hello! We have had to postpone HashiDays Sydney, but I'm not sure how to remove a conference from this list now?

HashiDays Sydney
Sydney, Australia・April 6-7

**Comment by nimzco** [comment]
Hey @AmandaPerino !
It’s never happens before, but you can remove it from the list here: https://github.com/tech-conferences/conference-data/blob/179bd8be86968c35e60196e4a554f81f6e40e9f1/conferences/2020/devops.json, then I’ll make sure it disappears from the website.

**Comment by AmandaPerino** [comment]
Thank you, we've merged it.
Appreciate your help.
