### ISSUE TITLE
Flutter App

### ISSUE THREAD

**Issue by leonardo2204** [tech-conferences/confs.tech#471]
Hey guys, in the past I started developing a [React-Native app](https://github.com/tech-conferences/confs.tech/issues/215), but I didn't have time to finish back then.

Fast-forward 2 years, I've started developing a flutter version, which will be in the stores in the next few days (it's in the approval queue).

I'd be happy to receive feedback and PR's in the repo: [https://github.com/leonardo2204/confstech-flutter](https://github.com/leonardo2204/confstech-flutter)

A few screenshots:

![Screenshot_1589386891](https://user-images.githubusercontent.com/1509421/82250771-7808c580-9922-11ea-8a84-fd8697e0b390.png)
![Screenshot_1589387334](https://user-images.githubusercontent.com/1509421/82250779-7ccd7980-9922-11ea-8d2c-83e3c184e8bc.png)
![Screenshot_1589387367](https://user-images.githubusercontent.com/1509421/82250784-7e973d00-9922-11ea-967d-6b847cce1d00.png)
![Screenshot_1589387380](https://user-images.githubusercontent.com/1509421/82250788-7fc86a00-9922-11ea-9051-a8ef39e3b00e.png)
![Screenshot_1589392067](https://user-images.githubusercontent.com/1509421/82250792-82c35a80-9922-11ea-9b42-7e4889ae51c0.png)

Thanks for the great work on the website!

**Comment by nimzco** [comment]
Oh man that’s amazing! Good work! 🎉

**Comment by nimzco** [comment]
I’ll have a look at the code when I have a moment. 👌🏼
And maybe it is be worth integrating the repo directly it in the tech-conference org!
cc @prigara @cgrail

**Comment by cgrail** [comment]
I also think it's great. 
@leonardo2204 if you want we can move the repo to the confs.tech organization.

@nimzco I've seen that the app is using the same Algolia applicationId and apiKey. Is that a problem? What are the rate limits?
https://github.com/leonardo2204/confstech-flutter/blob/c8ec16250c3fd3d48830a13cbb2faabb63f17c51/lib/repositories/event_repository.dart#L10

@leonardo2204 can you also please add a link to https://confs.tech instead of just the github repo?

Otherwise 👍

**Comment by nimzco** [comment]
We should be good for the apiKey and applicationId, the rates are unlimited when reading them as long as we display the `Powered by Algolia` badge somewhere on the search. I can probably create another key though. :)

**Comment by cgrail** [comment]
It seems like a link to Algolia is part of the about dialog:
https://github.com/leonardo2204/confstech-flutter/blob/c8ec16250c3fd3d48830a13cbb2faabb63f17c51/lib/dialog/about_dialog.dart#L101

**Comment by leonardo2204** [comment]
Hi guys, thanks for all the messages!
I was wondering if I should use the same key, if that's a problem I'm more than happy to change it, just send me the new keys and I'll change it.
I also changed the confs.tech URL, I'll be pushing it to master soon.

Regarding the Algolia logo, is that a problem to keep it in the about section? Or should I move it elsewhere?

Thanks again!

**Comment by prigara** [comment]
Hi @leonardo2204, that's awesome! Looking forward to installing that :) Great job!

**Comment by leonardo2204** [comment]
It is now live guys!!!
https://play.google.com/store/apps/details?id=leonardo2204.com.confs_tech

I'll be shipping the new version tomorrow with the comments above!

Try it out and let me know what you guys think!

Thanks

**Comment by RMPR** [comment]
Is it available on F-Droid?

**Comment by leonardo2204** [comment]
I don't think so :(

**Comment by RMPR** [comment]
Since the app is open source, it might be a good idea to submit it there https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by RMPR** [comment]
Since the app is open source, it might be a good idea to submit it there https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by nimzco** [comment]
Nice @leonardo2204 ! I don't have an android, but it really looks awesome!

**Comment by leonardo2204** [comment]
Hey @nimzco, my apple dev program expired a month ago and I didn't have time to set it up again :(

And I'll push some more fixes and move the repo to the organization!

P.S. I saw the location on the Confs-tech GitHub page, would you mind adding Brazil (my home country) 😝 

Thanks!

**Comment by nimzco** [comment]
Haha good call, I've added it! Such an international org! :p

**Comment by leonardo2204** [comment]
That's really cool haha! Thank you very much!
I've just transferred the ownership, it may take a couple of minutes to reflect the change!
