### ISSUE TITLE
Usage of your API

### ISSUE THREAD

**Issue by callain** [tech-conferences/confs.tech#472]
Hello !

I am developing for a side project a website for developers.
It's called "The Developer's Log". I aim to create a daily journal for developer.
At the moment it contains change logs of your github starred repositories.
The link is here: https://thedeveloperslog.coffee if you wanna try :)

I found out your website about dev conferences and saw that you have an algolia API with your data, which is awesome !

I would like to add a block with the next conferences (filterable by topic). In the website user can filtered some content by topic. Conferences will be filterable too :D

My question is, can I use your API (for search only) ? If yes do you have some documentation about facets and filters of your API ? I would like to know the best way to filter by topic

Thanks

**Comment by cgrail** [comment]
@nimzco

**Comment by callain** [comment]
Here is an example to what my app look likes. I have found my way to use topic filtering. Thanks to @leonardo2204 and its Flutter app ;)
I have put the conferences block on the top left, but it can be subject to move.

(Dev environment)
![image](https://user-images.githubusercontent.com/7001103/82929460-f77e4080-9f83-11ea-9ad3-a22bad77187c.png)

I am waiting your authorization before deploying it

**Comment by leonardo2204** [comment]
Cool visual! I still need to fix the filter part in the app though 😝

**Comment by nimzco** [comment]
Hey @callain that’s quite cool! 

I have no problem of you using the Algolia API key, the retrieval of the data is unlimited (if I’m not mistaken. They only limit the records and operations). You need to add their logo somewhere on the website though. ([See their doc](https://www.algolia.com/doc/faq/accounts-billing/do-i-need-to-display-the-algolia-logo-when-i-am-on-the-free-plan/))

Also, do you think you could add a small ref / link to confs.tech? Maybe a « See more on Confs.tech » link or something like that?

**Comment by callain** [comment]
Thank you for your approval :)

Like this ? 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/7001103/83326358-b92e9d00-a273-11ea-8233-905fb0a758b5.png">

**Comment by nimzco** [comment]
That’s perfect! Thank you very much and best of luck for your project! 🔥
