### ISSUE TITLE
Blank screen after clicking on sections

### ISSUE THREAD

**Issue by Ldoppea** [tech-conferences/confs.tech#478]
Hi,

Seems like the website is not working correctly anymore.

First display works correctly, but if I try to click on a category (General, DevOps etc) or a country (U.S.A, Germany etc), then everything disappears and I get a blank screen.

When checking for console errors, those two errors are thrown when clicking those sections:
![image](https://user-images.githubusercontent.com/1884255/105153479-c7823f80-5b08-11eb-9711-2d5f73622079.png)

This behavior is the same on chrome/brave/firefox and edge.

Maybe this commit fixes the bug (i don't have the tools to try). Do you confirm? https://github.com/tech-conferences/confs.tech/commit/efc4265d7951b60ec6410cd0ff13d1d3fee1494c

If so, you can close the issue 😄

**Comment by cgrail** [comment]
I'll take a look at it.

**Comment by cgrail** [comment]
Fixed with: https://github.com/tech-conferences/confs.tech/pull/479

**Comment by Ldoppea** [comment]
That was fast, thank you :)
