### ISSUE TITLE
Fix end date error when same date

### ISSUE THREAD

**Issue by nimzco** [tech-conferences/confs.tech#491]
# Steps to reproduce

- Go to http://localhost:3000/conferences/new
- Set start date same as end date
- See the error

<img width="535" alt="image" src="https://user-images.githubusercontent.com/445045/110645060-94296c00-81ad-11eb-8eb5-1965357a7bbb.png">

**Comment by cgrail** [comment]
Can you please check again. It works on my machine.
https://github.com/tech-conferences/conference-data/pull/3243
https://github.com/tech-conferences/conference-data/pull/3252

**Comment by nimzco** [comment]
Hmmm weird, it's not failing anymore... 🤔 

I'll close until I can reproduce more consistently.

**Comment by cgrail** [comment]
Ok. Would be great to know what is causing this error.
