### ISSUE TITLE
Feature Request:  want to show all past conferences with recorded video sites?

### ISSUE THREAD

**Issue by t829702** [tech-conferences/confs.tech#499]
the pandemic is bad to the tech industry all of us can't go attend the tech conferences in person; but also made many of the tech conferences switch to all virtual and all free to attend for all people world wide, and the virtual conferences were usually with recordings right away, not in the past even if a conference has video recordings but usually with many weeks delay

in the past need to pay high travel cost and could attend only a handful of conferences in person, now under the pandemic all of us can nearly pay zero (or very low) to attend many conferences, as many as wanted, or watch recordings if missed any live

I hope confs.tech can have such a simple url to show all past conferences, the most recent at the top, my purpose is not to attend cfp of future conferences, but want to learn things from the past, the more recent the better
https://confs.tech/past

**Comment by nimzco** [comment]
Hey @t829702, thanks for your comment.
There are no urls, but if you scroll to the bottom of the page you’ll see a button: « see past conferences ».

That should do the trick ;)

**Comment by t829702** [comment]
clicked that got this link, it's showing all the earliest one as 2016 as the top, and hard to scroll down and click next pages and pages till more recent 2021 latest; as you know the tech industry is changing so fast,  knowledge from 5 years ago is almost no use at all

and it's weird if I bookmark this link and open it directly it's still showing all future conferences only
https://confs.tech/?online=true&offersSignLanguageOrCC=false&continents=&countries=&topics=

**Comment by nimzco** [comment]
You're totally right.
What do you think of this behaviour: https://60795c2505362d0007f63325--confs-tech.netlify.app

**Comment by t829702** [comment]
right, but the ordering is still not right: why does it show Nov/2020 at the top, can be changed to show recent Apr/2021 at the top?

![image](https://user-images.githubusercontent.com/49542456/115061485-d92c7680-9eae-11eb-99ce-a84ca1063803.png)

**Comment by nimzco** [comment]
Ah didn't think of that. I was going backward in my mind. 

That's a good idea though. I'll try what you're suggesting next week and will share an update.

I will probably need to add a small text showing the sort order to make sure it's clear for everyone.

**Comment by nimzco** [comment]
@t829702 What do you think of this version: https://607d6baa107d4f0007a7ffd3--confs-tech.netlify.app
There is a "Past conferences" link at the top of the page now.

**Comment by nimzco** [comment]
Will close this issue since I've merged https://github.com/tech-conferences/confs.tech/pull/500
