### ISSUE TITLE
Feature Request: Calendar View

### ISSUE THREAD

**Issue by t829702** [tech-conferences/confs.tech#501]
Something like this https://lwn.net/Calendar/Monthly/2021-05/ is showing a straightforward view of which conferences will be held on weekends; or which will be on weekdays which will be conflicts with my work, or I will have to request some time off in advance if I really want to attend;

![image](https://user-images.githubusercontent.com/49542456/115137020-1ac13c80-9fe9-11eb-8878-e25c9442114d.png)

I hope https://confs.tech/ can have a calendar view of conferences in the following 3 months, better than a single month view; we are caring more of near future than far future, also because many conferences don't have details until 3 months before it (or even closer); but don't mind if it can also have a future 12-months view

**Comment by t829702** [comment]
or with #402 #444 feed for gCalendar or iCalendar  use one's own calendar

**Comment by nimzco** [comment]
Would this do the trick for you: https://confs-tech-api.herokuapp.com/api/conferences.rss ?

**Comment by t829702** [comment]
yes, RSS is a good way I can import into my client side calendar management,

but it seems showing only 15 items, does it have parameters can show more items?

    $ curl https://confs-tech-api.herokuapp.com/api/conferences.rss | grep description
    <description>Confs.tech | List of tech conferences: JavaScript, UX / Design, Ruby</description>
      <description>📍 Portorož, Slovenia &amp; Online | October, 11 | #java</description>
      <description>📍 Online | November, 23 | #data</description>
      <description>📍 Online | June, 2 | #javascript</description>
      <description>📍 Munich, Germany &amp; Online | November, 8 | #java</description>
      <description>📍 Munich, Germany &amp; Online | October, 25 | #php</description>
      <description>📍 Online | June, 17 | #java</description>
      <description>📍 Online | June, 8 | #devops</description>
      <description>📍 Online | May, 26 | #general</description>
      <description>📍 Online | August, 12 | #kotlin</description>
      <description>📍 Split, Croatia &amp; Online | September, 7 | #general</description>
      <description>📍 Online | September, 27 | #ios</description>
      <description>📍 Online | September, 15 | #leadership</description>
      <description>📍 Gdansk, Poland &amp; Online | October, 14 | #general</description>
      <description>📍 Online | June, 15 | #javascript</description>
      <description>📍 Online | June, 17 | #php</description>

**Comment by nimzco** [comment]
Hey @t829702, I've added a limit params that can go up to 50. ;)

**Comment by t829702** [comment]
> Eg: https://confs-tech-api.herokuapp.com/api/conferences.rss?limit=17

Application error

**Comment by nimzco** [comment]
Thanks for reporting @t829702, I've fixed the issue ;)

**Comment by nimzco** [comment]
I'll close the issue now.
