### ISSUE TITLE
Filter that shows only conferences that are in-person

### ISSUE THREAD

**Issue by chiptopher** [tech-conferences/confs.tech#502]
I'm imagining even as things open up there will still be a number of conferences that stay online indefinitely, so it'd be cool if we could somehow remove online-only conferences from the list. It'd be similar to how "Online conferences" works, but the opposite.

Thanks for putting this project together!

**Comment by nimzco** [comment]
Hey @chiptopher, that's a good idea. I'll try to take some time to see what I can do about that :)

**Comment by nimzco** [comment]
Hey @chiptopher what do you think about that? 
https://deploy-preview-503--confs-tech.netlify.app

cc @cgrail 😄

**Comment by chiptopher** [comment]
Love it 🚀

**Comment by nimzco** [comment]
Awesome! 🎉
I’m merging the PR then!
