### ISSUE TITLE
Bug report, Top Level Domain is crashing.

### ISSUE THREAD

**Issue by ChristianBako** [tech-conferences/confs.tech#504]
TLD Is crashing on Firefox, probably due to a react bug. 
<img width="2047" alt="Screen Shot 2021-08-03 at 9 47 29 AM" src="https://user-images.githubusercontent.com/3161694/128054532-11aff48d-0970-45bf-b263-881716aa49ef.png">

The other urls look ok.
<img width="2048" alt="Screen Shot 2021-08-03 at 9 47 47 AM" src="https://user-images.githubusercontent.com/3161694/128054569-6e477066-3fd8-4748-99cf-257bc0e1dbe9.png">

**Comment by nimzco** [comment]
Ah shoe! Thanks for reporting it, I’ll check this as soon as I can.

**Comment by nimzco** [comment]
It’s probably coming from a malformatted conference date.

**Comment by nimzco** [comment]
This will probably do the trick: https://github.com/tech-conferences/conference-data/pull/3687

**Comment by ChristianBako** [comment]
Thank you!
