### ISSUE TITLE
Pull in Testing conferences

### ISSUE THREAD

**Issue by FloorD** [tech-conferences/confs.tech#506]
Any chance you could pull from https://testingconferences.org/ under a separate `Testing` category? I think now people have listed software testing conferences under either `General`, or `DevOps` and it's getting unwieldy. 🙏

**Comment by nimzco** [comment]
Sure thing, I'll do that right away ;)
(You couldn't submit the issue on a better timing 😄)

**Comment by nimzco** [comment]
https://github.com/tech-conferences/conference-data/pull/3701 😇

**Comment by FloorD** [comment]
Yay! Thank you!

**Comment by nimzco** [comment]
🙌🏼
