### ISSUE TITLE
Seeing the past conferences

### ISSUE THREAD

**Issue by prigara** [tech-conferences/confs.tech#59]
It would be great to be able to see the past conferences.
You may want it: 1. to see the recordings of the talks; or 2. to check that the new date of the conference was announced.

We can add a small link `See past conferences` on top (or at the bottom) of the main list  that will take you to confs.tech/<category>/<year>.

What do you think?

**Comment by nimzco** [comment]
Hum, I had this link before but removed to keep it simple and I didn't have a use case for why you would want it. 🤔
I get your first point but at the same time, if that's what you want you probably know the name of the conference and will google it?
And the second point: hopefully if a new date of the conference is announced it will be in the list?

But I can try to come up with something and we could also track if people click on the link to see if it's used?

**Comment by prigara** [comment]
> I get your first point but at the same time, if that's what you want you probably know the name of the conference and will google it?

Might also be that you don't know the name. Say, you're interested in React, then you can go though the list to find some React-related past events (and often you can pretty much guess from the conference name what it's about), see the videos, and maybe decide to keep an eye on it to go next year.

> And the second point: hopefully if a new date of the conference is announced it will be in the list?

I used to go through the list of past events myself to add new dates. It's more like an "editor" task, maybe not so common, but now I would have to go through JSON.

**Comment by nimzco** [comment]
Fair enough! I actually just realized looking back at the code that the functionality was still there.

It just shows the conferences that are hidden for the current year for now so it will fall appart in January, but I'll try to find a fix it before then!

I've added back the link in the footer, let me know what you think.

**Comment by prigara** [comment]
Thanks! Can you please also add a year at the beginning of every year in the list?

**Comment by nimzco** [comment]
Yes! I wanted to do it but forgot at some point! 
Here they are 🙌🏼

**Comment by prigara** [comment]
Great! Thank you :)
