### ISSUE TITLE
Integrate GitHub star

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/confs.tech#648]
Integrate GitHub star count to showcase project popularity and credibility, fostering future contributions.

1 or 2?
![image](https://github.com/tech-conferences/confs.tech/assets/25883220/d5582891-cbc4-4f12-9229-f1ad251dddfd)

**Comment by cgrail** [comment]
Hmm. I think 1. thanks a lot.

**Comment by JuanPabloDiaz** [comment]
After some digging, I found a component called [GithubStar.tsx](https://github.com/tech-conferences/confs.tech/blob/main/src/components/GithubStar/GithubStar.tsx) that does exactly what we need. Looks like it's not being used anywhere.

I managed to put it in spot 2, but still figuring out how to get it in spot 1 lol.

![image](https://github.com/tech-conferences/confs.tech/assets/25883220/c18e7162-691d-4f23-a235-4085c1e24721)

**Comment by nimzco** [comment]
Ah that's true, we have that at some point and I removed it, but I don't remember why.

**Comment by JuanPabloDiaz** [comment]
Let me add it back
