### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/confs.tech#669]
I am exploring GitHub Actions and was wondering if there is one in particular that you could recommend for JS projects?

I have been testing a couple of them but not sure if we even need them.

I tested [is-website-vulnerable](https://github.com/marketplace/actions/is-website-vulnerable) and it didn't find any errors. [test here](https://github.com/JuanPabloDiaz/confs.tech/pull/2)

Please let me know,

**Comment by nimzco** [comment]
Shouldn't this be enough? https://github.com/tech-conferences/confs.tech/security

**Comment by JuanPabloDiaz** [comment]
Probable. The test did not catch any vulnerabilities.
