### ISSUE TITLE
https://confs.tech/ Showing Blank Screen 

### ISSUE THREAD

**Issue by chandanrjit** [tech-conferences/confs.tech#698]
![image](https://github.com/user-attachments/assets/b9fa0330-4191-42f1-b92a-12b097a46066)
 Some DOM error 
![image](https://github.com/user-attachments/assets/3591ebf8-a66e-4d13-9ce7-7c83e6586543)

**Comment by nimzco** [comment]
Oh thank you for reporting this, it happened because of our recent plugin updates.
This should fix it, I tried it locally: https://github.com/tech-conferences/confs.tech/pull/699

**Comment by nimzco** [comment]
It's fixed! Thanks again! 🙏🏼 
https://confs.tech

**Comment by chandanrjit** [comment]
all good mate. cheers
