### ISSUE TITLE
General conferences are not loading

### ISSUE THREAD

**Issue by trivikr** [tech-conferences/confs.tech#76]
URL: https://confs.tech/general

Seems to be a malformed JSON
Error in Console `SyntaxError: Unexpected token { in JSON at position 1101`

![screen shot 2017-11-13 at 8 00 04 pm](https://user-images.githubusercontent.com/16024985/32762285-744343dc-c8ad-11e7-91e2-1fc8c03043a1.png)

**Comment by nimzco** [comment]
It's fixed and live! https://confs.tech/general 🙌🏼
Thanks!
