### ISSUE TITLE
[Feature Request] RSS Feed

### ISSUE THREAD

**Issue by tomershvueli** [tech-conferences/confs.tech#809]
Love this concept and the site as a whole! 

Would you be able to add an RSS feed such that whenever a new conference gets added to the site it results in a new RSS feed item? 

Thanks! 

Tomer

**Comment by nimzco** [comment]
Hey @tomershvueli!
We actually have rss links that I’ve never added to the UI. You can find the links here:
https://github.com/tech-conferences/confs.tech/issues/402#issuecomment-2015406577

**Comment by nimzco** [comment]
Great! Glad it helped!
