### ISSUE TITLE
Pixel Up!

### ISSUE THREAD

**Issue by mr-farai** [tech-conferences/confs.tech#81]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "Pixel Up!",
    "url": "https://pixelup.co.za",
    "startDate": "2018-03-12",
    "endDate": "2018-03-14",
    "city": "Johannesburg",
    "country": "South Africa",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@letspixelup"
  }
```

**Comment by nimzco** [comment]
Awesome, thanks! 👍
