### ISSUE TITLE
ADDC

### ISSUE THREAD

**Issue by MatejBalantic** [tech-conferences/confs.tech#83]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [x] UX / Design
- [x] iOS
- [ ] Ruby

```json
  {
    "name": "ADDC - App Design & Development Conference",
    "url": "https://addconf.com",
    "startDate": "2018-07-04",
    "endDate": "2018-07-06",
    "city": "Barcelona",
    "country": "Spain",
    "cfpUrl": "https://addconf.com/2018/call-for-proposals/",
    "cfpEndDate": "2017-02-15",
    "twitter": "@addconf"
  }
```

**Comment by nimzco** [comment]
I've added it, thanks! 👍
