### ISSUE TITLE
Add ReactFest to JS conference list

### ISSUE THREAD

**Issue by kittysquee** [tech-conferences/confs.tech#84]
Hey, here is a conference that is missing from the list.

Where should it go?
- [x] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] UX / Design
- [ ] iOS
- [ ] Ruby

```json
  {
    "name": "ReactFest",
    "url": "https://reactfest.com/",
    "startDate": "2018-03-09",
    "endDate": "2018-03-09",
    "city": "London",
    "country": "U.K.",
    "cfpUrl": "https://docs.google.com/forms/d/e/1FAIpQLScACeKKR_21RSDcKUxfsjLd1jCCeq-QHxll78gF99rmQCcljA/viewform",
    "cfpEndDate": "2018-01-15",
    "twitter": "@ReactFest"
  }
```

**Comment by kittysquee** [comment]
Add ReactFest to conference list.

**Comment by nimzco** [comment]
I've added it, thanks! 👍
