### ISSUE TITLE
Chicago Roboto 2018

### ISSUE THREAD

**Issue by jwilker** [tech-conferences/confs.tech#87]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] UX / Design
- [ ] iOS
- [X] Android
- [ ] Ruby
- [ ] General

```json
  {
    "name": "Chicago Roboto",
    "url": "http://chicagoroboto.com",
    "startDate": "2018-04-12",
    "endDate": "2018-04-13",
    "city": "Chicago, IL",
    "country": "USA",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@chicagoroboto"
  }
```

**Comment by nimzco** [comment]
👍 Thanks!
