### ISSUE TITLE
360|AnDev 2018

### ISSUE THREAD

**Issue by jwilker** [tech-conferences/confs.tech#88]
Hey, here is a conference that is missing from the list.

Where should it go?
- [ ] JavaScript => [Add it to the JavaScript Conference](https://github.com/tech-conferences/javascript-conferences/issues/new)
- [ ] UX / Design
- [ ] iOS
- [X] Android
- [ ] Ruby
- [ ] General

```json
  {
    "name": "360|AnDev",
    "url": "https://360andev.com",
    "startDate": "2018-07-19",
    "endDate": "2018-07-20",
    "city": "Denver, CO",
    "country": "USA",
    "cfpUrl": "https://360andev.com/call-for-papers/",
    "cfpEndDate": "2018-04-06",
    "twitter": "@360andev"
  }
```

**Comment by nimzco** [comment]
Thanks, I've just added it!
